Feature: Report only submission
    Partners, redhat and community users can publish their chart by submitting
    error-free report that was generated by chart-verifier.


    Scenario Outline: [HC-12-001] A partner or redhat associate submits an error-free report
        Given the vendor <vendor> has a valid identity as <vendor_type>
        And an error-free report is used in <report_path>
        When the user sends a pull request with the report
        Then the user sees the pull request is merged
        And the index.yaml file is updated with an entry for the submitted chart
    
        Examples:
            | vendor_type  | vendor    | report_path               |
            | partners     | hashicorp | tests/data/report.yaml    |
            | redhat       | redhat    | tests/data/report.yaml    |

    Scenario Outline: [HC-12-002] A community user submits an error-free report
        Given the vendor <vendor> has a valid identity as <vendor_type>
        And an error-free report is used in <report_path>
        When the user sends a pull request with the report
        Then the pull request is not merged
        And user gets the <message> in the pull request comment

        Examples:
            | vendor_type   | vendor    | report_path              | message                                                                                     |
            | community     | redhat    | tests/data/report.yaml   | Community charts require maintainer review and approval, a review will be conducted shortly |

    Scenario Outline: [HC-12-003] A partner or redhat associate submits report only with dash in chart version
        Given the vendor <vendor> has a valid identity as <vendor_type>
        And an error-free report is used in <specific_report_path>
        When the user sends a pull request with the report
        Then the user sees the pull request is merged
        And the index.yaml file is updated with an entry for the submitted chart

        Examples:
            | vendor_type  | vendor    | specific_report_path |
            | partners     | hashicorp | tests/data/HC-12/dash-in-version/report.yaml |
            | redhat       | redhat    | tests/data/HC-12/dash-in-version/report.yaml |

