apiversion: v1
kind: verify-report
metadata:
  chart:
    annotations:
      charts.openshift.io/archs: x86_64
      charts.openshift.io/name: PSQL RedHat Demo Chart
      charts.openshift.io/provider: RedHat
      charts.openshift.io/supportURL: https://github.com/dperaza4dustbit/helm-chart
    apiversion: v2
    appversion: 10.0.0
    condition: ''
    dependencies: []
    deprecated: false
    description: A Helm chart for a RedHat Certified PSQL
    home: ''
    icon: ''
    keywords: []
    kubeversion: '>=1.20.0'
    maintainers: []
    name: psql-service
    sources: []
    tags: ''
    type: application
    version: 0.1.10-1
  chart-overrides: ''
  tool:
    chart-uri: https://github.com/openshift-helm-charts/development/blob/main/tests/data/psql-service-0.1.10-1.tgz?raw=true
    digests:
      chart: sha256:db482b4d90349c6b276ba27f581720cc62fa7bea05184b5bfd840844178a8da6
      package: c8635dcdc8f8493abbdef85305be55c9d5dbf3a44495a88a8285c9a0d0c63408
    lastCertifiedTimestamp: '2022-06-22T17:21:03.1478+00:00'
    profile:
      VendorType: redhat
      version: v1.1
    providerControlledDelivery: false
    supportedOpenShiftVersions: '>=4.7'
    testedOpenShiftVersion: '4.10'
    verifier-version: 1.7.0
results:
- check: v1.0/has-readme
  outcome: PASS
  reason: Chart has a README
  type: Mandatory
- check: v1.0/is-helm-v3
  outcome: PASS
  reason: API version is V2, used in Helm 3
  type: Mandatory
- check: v1.0/not-contains-crds
  outcome: PASS
  reason: Chart does not contain CRDs
  type: Mandatory
- check: v1.0/not-contain-csi-objects
  outcome: PASS
  reason: CSI objects do not exist
  type: Mandatory
- check: v1.0/images-are-certified
  outcome: PASS
  reason: 'Image is Red Hat certified : registry.access.redhat.com/rhscl/postgresql-10-rhel7:1-66'
  type: Mandatory
- check: v1.0/chart-testing
  outcome: PASS
  reason: Chart tests have passed
  type: Mandatory
- check: v1.0/required-annotations-present
  outcome: PASS
  reason: All required annotations present
  type: Mandatory
- check: v1.0/contains-test
  outcome: PASS
  reason: Chart test files exist
  type: Mandatory
- check: v1.0/contains-values
  outcome: PASS
  reason: Values file exist
  type: Mandatory
- check: v1.0/contains-values-schema
  outcome: PASS
  reason: Values schema file exist
  type: Mandatory
- check: v1.1/has-kubeversion
  outcome: PASS
  reason: Kubernetes version specified
  type: Mandatory
- check: v1.0/helm-lint
  outcome: PASS
  reason: Helm lint successful
  type: Mandatory
