# -*- coding: utf-8 -*-
"""Report only submission

Partners or redhat associates can publish their chart by submitting
error-free report that was generated by chart-verifier.
"""
import os
import json
import base64
import pathlib
import logging
from tempfile import TemporaryDirectory
from dataclasses import dataclass
from string import Template

import git
import yaml
import pytest
from pytest_bdd import (
    given,
    scenario,
    then,
    when,
)

from functional.utils.utils import *
from functional.utils.certification_workflow_test import CertificationWorkflowTestOneShot

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)


@pytest.fixture
def workflow_test():
    test_report = 'tests/data/report.yaml'
    workflow_test = CertificationWorkflowTestOneShot(test_report=test_report)
    yield workflow_test
    workflow_test.cleanup()


@scenario('features/report_without_chart.feature', "The partner hashicorp submits a error-free report for the vault chart")
def test_partner_submits_report_without_any_errors():
    """The partner hashicorp submits a error-free report for the vault chart."""


@scenario('features/report_without_chart.feature', "The redhat associate submits a error-free report for the vault chart")
def test_redhat_submits_report_without_any_errors():
    """The redhat associate submits a error-free report for the vault chart."""


@given("hashicorp is a valid partner")
def hashicorp_is_a_valid_partner(workflow_test):
    """hashicorp is a valid partner"""
    workflow_test.set_vendor(get_unique_vendor('hashicorp'), 'partners')


@given("a redhat associate has a valid identity")
def redhat_associate_is_valid(workflow_test):
    """a redhat associate has a valid identity"""
    workflow_test.set_vendor(get_unique_vendor('redhat'), 'redhat')


@given("hashicorp has created a error-free report")
@given("the redhat associate has created a report without any errors")
def the_user_has_created_a_report_without_errors(workflow_test):
    """The user has created a report without any errors."""
    workflow_test.setup_git_context()
    workflow_test.setup_gh_pages_branch()
    workflow_test.setup_temp_dir()
    workflow_test.process_owners_file()
    workflow_test.process_report()


@when("hashicorp sends a pull request with the report")
@when("the redhat associate sends the pull request with the report")
def the_user_sends_the_pull_request_with_the_report(workflow_test):
    """The user sends the pull request with the report."""
    workflow_test.send_pull_request()


@then("hashicorp sees the pull request is merged")
@then("the redhat associate sees the pull request is merged")
def the_user_should_see_the_pull_request_getting_merged(workflow_test):
    """The user should see the pull request getting merged."""
    workflow_test.check_workflow_conclusion()
    workflow_test.check_pull_request_result()


@then("the index.yaml file is updated with an entry for the submitted chart")
def the_index_yaml_is_updated_with_a_new_entry(workflow_test):
    """The index.yaml file is updated with a new entry."""
    workflow_test.check_index_yaml()
