name: Test Workflow

on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Run tests but do not create issues {true,false}'
        required: true
        default: 'true'
      notify-id:
        description: 'Issue notification {github id}'
        required: false
        default: ''
      vendor-type:
        description: 'Vendor type {all,partner,redhat,community}'
        required: true
        default: 'all'
      software-name:
        description: 'Software Name'
        required: true
      software-version:
        description: 'Software Version'
        required: true


jobs:
  workflow-test:
    name: Workflow Test
    runs-on: ubuntu-20.04
    if: github.event.pull_request.draft == false

    steps:
      # - name: Configure Git
      #   run: |
      #     git config --global user.name "github-actions[bot]"
      #     git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Create new temporary branch
        run: |
          # git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git remote -v
          git branch -vv
          # HEAD=$(git rev-parse --short HEAD)
          # echo "head=${HEAD}" >> $GITHUB_ENV
          # git checkout -b ${HEAD}
          # git push origin ${HEAD}
        shell: bash

      # - name: Push to Origin
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ env.head }}

      - name: Set up Python 3.x Part 1
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Set up Python 3.x Part 2
        run: |
          # set up python requirements and scripts
          python3 -m venv ve1
          cd scripts && ../ve1/bin/pip3 install -r requirements.txt && cd ..
          cd scripts && ../ve1/bin/python3 setup.py install && cd ..

      - name: Check Request
        id: check_request
        run: |
          # check if workflow testing should run.
          echo "Request type: $GITHUB_EVENT_NAME"
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
              echo "[INFO] check if PR contains only workflow changes and user is authorized"
              ve1/bin/check-pr-for-ci --verify-user=${{ github.event.pull_request.user.login }} --api-url=${{ github.event.pull_request._links.self.href }}
          else
              echo "[INFO] manual invocation - check if user is authorized"
              ve1/bin/check-pr-for-ci --verify-user=${{ github.actor }}
          fi

      - name: Test CI Workflow
        id: test_ci_workflow
        if: ${{ steps.check_request.outputs.run-tests == 'true'}}
        env:
          CLUSTER_TOKEN: ${{ secrets.CLUSTER_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRY_RUN: ${{ github.event.inputs.dry-run }}
          VENDOR_TYPE: ${{ github.event.inputs.vendor-type }}
          NOTIFY_ID: ${{ github.event.inputs.notify-id }}
          SOFTWARE_NAME: ${{ github.event.inputs.software-name }}
          SOFTWARE_VERSION: ${{ github.event.inputs.software-version }}
          BOT_NAME: github-actions[bot]
          BOT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Run the wokflow tests
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
              ve1/bin/pytest tests/functional/test_report_only_no_errors.py --log-cli-level=INFO --ignore=tests/functional/test_submitted_charts.py
          else
              echo "[INFO] Dry run ${{ env.DRY_RUN }}"
              echo "[INFO] Vendor type ${{ env.VENDOR_TYPE }}"
              echo "[INFO] Notify ID ${{ env.NOTIFY_ID }}"
              echo "[INFO] Software Name ${{ env.SOFTWARE_NAME }}"
              echo "[INFO] Software Version ${{ env.SOFTWARE_VERSION }}"
              ve1/bin/pytest tests/functional/test_submitted_charts.py --log-cli-level=INFO
          fi
